Neos:
  Fusion:
    defaultContext:
      Mjml: 'PunktDe\Neos\Mjml\MjmlHelper'

PunktDe:
  Neos:
    Mjml:
      # Use the variable {PACKAGEROOT} for an absolute path to this package directory
      mjmlBinPath: '{PACKAGEROOT}/Resources/Private/Library/node_modules/bin/mjml'


