Neos:
  Fusion:
    defaultContext:
      Mjml: 'PunktDe\Neos\Mjml\MjmlHelper'

PunktDe:
  Neos:
    Mjml:
      # Use the variable {PACKAGERESOURCEROOT} for an absolute path to this package directory
      mjmlBinPath: '{PACKAGERESOURCEROOT}Private/Library/node_modules/mjml/bin/mjml'
